version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "pip enviroments"
      include: "scope  
    open-pull-requests-limit: 5  
  - package-ecosystem: 'github-actions'
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5
