    # Generated by Django 3.1.3 on 2020-11-26 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acessorios', '0001_initial'),
        ('informacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacaDeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Placa de video',
                'verbose_name_plural': 'Placas de video',
            },
        ),
        migrations.CreateModel(
            name='Processador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(choices=[('INTEL', 'INTEL'), ('AMD', 'AMD'), ('INTEL E AMD', 'INTEL E AMD')], max_length=100)),
                ('descricao', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Processador',
                'verbose_name_plural': 'Processadores',
            },
        ),
        migrations.CreateModel(
            name='PlacaMae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('marca', models.CharField(choices=[('INTEL', 'INTEL'), ('AMD', 'AMD'), ('INTEL E AMD', 'INTEL E AMD')], max_length=100)),
                ('slots', models.IntegerField(default=0)),
                ('videoIntegrado', models.BooleanField(default=False)),
                ('descricao', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acessorios.cores')),
                ('memoriaSuportada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informacoes.tamanhos')),
            ],
            options={
                'verbose_name': 'Placa Mãe',
                'verbose_name_plural': 'Placas Mãe',
            },
        ),
        migrations.CreateModel(
            name='MemoriaRam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cor', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('totalGigas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informacoes.tamanhos')),
            ],
            options={
                'verbose_name': 'Memoria',
                'verbose_name_plural': 'Memorias',
            },
        ),
    ]
