# Generated by Django 3.1.3 on 2020-11-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memoriaram',
            options={'verbose_name': 'Memoria Ram', 'verbose_name_plural': 'Memorias'},
        ),
        migrations.AlterModelOptions(
            name='placadevideo',
            options={'verbose_name': 'Placa de video', 'verbose_name_plural': 'Placas de video'},
        ),
        migrations.AlterModelOptions(
            name='placamae',
            options={'verbose_name': 'Placa Mãe', 'verbose_name_plural': 'Placas Mãe'},
        ),
        migrations.AlterModelOptions(
            name='processador',
            options={'verbose_name': 'Processador', 'verbose_name_plural': 'Processadores'},
        ),
    ]
