# Generated by Django 3.1.3 on 2021-01-21 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memoriaram',
            old_name='totalGigas',
            new_name='total_gigas',
        ),
        migrations.RenameField(
            model_name='placamae',
            old_name='memoriaSuportada',
            new_name='memoria_suportada',
        ),
        migrations.RenameField(
            model_name='placamae',
            old_name='videoIntegrado',
            new_name='video_integrado',
        ),
    ]
