# Generated by Django 3.1.3 on 2020-11-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20201116_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processador',
            old_name='nome',
            new_name='marca',
        ),
        migrations.AddField(
            model_name='placamae',
            name='processador',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
