# Generated by Django 3.1.2 on 2021-02-05 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20210121_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoriaram',
            name='quantidade',
        ),
    ]
