# Generated by Django 3.1.3 on 2020-11-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20201116_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placamae',
            name='processador',
        ),
        migrations.AddField(
            model_name='memoriaram',
            name='tamanho',
            field=models.CharField(choices=[('opcao1', '4 GB'), ('opcao2', '8 GB'), ('opcao3', '16 GB'), ('opcao4', '32 GB'), ('opcao5', '64 GB')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placamae',
            name='memoriaSuportada',
            field=models.CharField(choices=[('opcao1', 'Até 16 GB'), ('opcao2', 'Até 64 GB')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placamae',
            name='processadorSuportado',
            field=models.CharField(choices=[('INTEL', 'INTEL'), ('AMD', 'AMD'), ('INTEL_AMD', 'INTEL E AMD')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placamae',
            name='slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='placamae',
            name='videoIntegrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processador',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processador',
            name='marca',
            field=models.CharField(choices=[('INTEL', 'INTEL'), ('AMD', 'AMD')], max_length=100),
        ),
    ]
