# Generated by Django 3.1.2 on 2021-02-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_memoriaram_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placamae',
            name='memoria_suportada',
            field=models.PositiveIntegerField(choices=[(8, 8), (16, 16), (32, 32), (64, 64)]),
        ),
    ]
