# Generated by Django 3.1.2 on 2021-02-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20210206_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoriaram',
            name='total_gigas',
        ),
        migrations.AddField(
            model_name='memoriaram',
            name='memoria_suportada',
            field=models.PositiveIntegerField(choices=[(8, 8), (16, 16), (32, 32), (64, 64)], default=8),
            preserve_default=False,
        ),
    ]
