# Generated by Django 3.1.3 on 2020-11-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20201117_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placamae',
            name='processadorSuportado',
            field=models.CharField(choices=[('INTEL', 'INTEL'), ('AMD', 'AMD'), ('INTEL & AMD', 'INTEL & AMD')], max_length=100),
        ),
        migrations.AlterField(
            model_name='placamae',
            name='slots',
            field=models.CharField(choices=[('2', '2'), ('4', '4')], max_length=10),
        ),
    ]
