# Generated by Django 3.1.3 on 2020-11-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20201117_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoriaram',
            name='tamanho',
            field=models.CharField(choices=[('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB')], max_length=100),
        ),
        migrations.AlterField(
            model_name='placamae',
            name='memoriaSuportada',
            field=models.CharField(choices=[('Até 16 GB', 'Até 16 GB'), ('Até 64 GB', 'Até 64 GB')], max_length=100),
        ),
    ]
