# Generated by Django 3.1.3 on 2020-11-17 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20201117_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamanhos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('opcao1', '4 GB'), ('opcao2', '8 GB'), ('opcao3', '16 GB'), ('opcao4', '32 GB'), ('opcao5', '64 GB')], max_length=100)),
            ],
            options={
                'verbose_name': 'Tamanho',
                'verbose_name_plural': 'Tamanhos',
            },
        ),
        migrations.AddField(
            model_name='memoriaram',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='memoriaram',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='placadevideo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2020-1-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placadevideo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='placamae',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2020-1-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placamae',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='processador',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2020-1-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processador',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='placamae',
            name='processadorSuportado',
            field=models.CharField(choices=[('INTEL', 'INTEL'), ('AMD', 'AMD'), ('INTEL_AMD', 'INTEL E AMD')], max_length=100),
        ),
        migrations.AlterField(
            model_name='placamae',
            name='slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memoriaram',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.tamanhos'),
        ),
    ]
