# Generated by Django 3.1.3 on 2020-11-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_auto_20201117_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoriaram',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='memoriaram',
            name='tamanho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.tamanhos'),
        ),
    ]
