# Generated by Django 3.1.3 on 2020-11-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_auto_20201117_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamanhos',
            name='tamanho',
            field=models.CharField(choices=[('4 GB', '4 GB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB')], max_length=100),
        ),
    ]
