# Generated by Django 3.1.3 on 2020-11-17 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_auto_20201117_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcas', models.CharField(choices=[('INTEL', 'INTEL'), ('AMD', 'AMD'), ('INTEL_AMD', 'INTEL E AMD')], max_length=100)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.RemoveField(
            model_name='placamae',
            name='processadorSuportado',
        ),
        migrations.AlterField(
            model_name='placamae',
            name='slots',
            field=models.CharField(choices=[('2', '2'), ('4', '4')], max_length=20),
        ),
        migrations.AddField(
            model_name='placamae',
            name='marca',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='produtos.marcas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processador',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.marcas'),
        ),
    ]
