# Generated by Django 3.1.1 on 2020-11-18 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0001_initial'),
        ('acessorios', '0002_auto_20201117_2236'),
        ('produtos', '0010_auto_20201117_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memoriaram',
            options={'verbose_name': 'Memoria', 'verbose_name_plural': 'Memorias'},
        ),
        migrations.AddField(
            model_name='memoriaram',
            name='cor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acessorios.cores'),
        ),
        migrations.AddField(
            model_name='placamae',
            name='cor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acessorios.cores'),
        ),
        migrations.AlterField(
            model_name='memoriaram',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informacoes.tamanhos'),
        ),
        migrations.AlterField(
            model_name='placamae',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informacoes.marcas'),
        ),
        migrations.AlterField(
            model_name='processador',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informacoes.marcas'),
        ),
        migrations.DeleteModel(
            name='Marcas',
        ),
        migrations.DeleteModel(
            name='Tamanhos',
        ),
    ]
