# Generated by Django 3.1.3 on 2020-11-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_auto_20201117_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='placadevideo',
            name='none',
            field=models.BooleanField(default=False),
        ),
    ]
