# Generated by Django 3.1.3 on 2020-11-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_placadevideo_none'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoriaram',
            name='descricao',
            field=models.CharField(default='teste', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placadevideo',
            name='descricao',
            field=models.CharField(default='VERDADEIRO', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placamae',
            name='descricao',
            field=models.CharField(default='teste', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processador',
            name='descricao',
            field=models.CharField(default='efasef', max_length=150),
            preserve_default=False,
        ),
    ]
