# Generated by Django 3.1.1 on 2020-11-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_auto_20201120_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placamae',
            name='marca',
            field=models.CharField(choices=[('INTEL', 'INTEL'), ('AMD', 'AMD'), ('INTEL_AMD', 'INTEL E AMD')], max_length=100),
        ),
        migrations.AlterField(
            model_name='processador',
            name='marca',
            field=models.CharField(choices=[('INTEL', 'INTEL'), ('AMD', 'AMD'), ('INTEL_AMD', 'INTEL E AMD')], max_length=100),
        ),
    ]
