# Generated by Django 3.1.1 on 2020-11-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0017_auto_20201124_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoriaram',
            name='quantidade',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('4', '4')], max_length=100, null=True),
        ),
    ]
