# Generated by Django 3.1.1 on 2020-11-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0018_auto_20201124_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoriaram',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='placamae',
            name='slots',
            field=models.IntegerField(default=0),
        ),
    ]
