# Generated by Django 3.1.1 on 2020-11-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0019_auto_20201124_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoriaram',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='memoriaram',
            name='totalGigas',
            field=models.CharField(choices=[('4', '4 GB'), ('8', '8 GB'), ('16', '16 GB'), ('32', '32 GB'), ('64', '64 GB')], default='4', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placamae',
            name='memoriaSuportada',
            field=models.CharField(choices=[('16', 'Até 16 GB'), ('64', 'Até 64 GB')], max_length=100),
        ),
    ]
