# Generated by Django 3.1.3 on 2020-11-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0020_auto_20201124_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placadevideo',
            name='none',
        ),
    ]
