# Generated by Django 3.1.1 on 2020-11-25 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0004_auto_20201125_2034'),
        ('produtos', '0021_remove_placadevideo_none'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoriaram',
            name='totalGigas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informacoes.tamanhos'),
        ),
        migrations.AlterField(
            model_name='placamae',
            name='memoriaSuportada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informacoes.tamanhos'),
        ),
    ]
