# Generated by Django 3.1.1 on 2020-11-26 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0004_auto_20201125_2034'),
        ('produtos', '0022_auto_20201125_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placamae',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informacoes.marcas'),
        ),
    ]
