# Generated by Django 3.1.1 on 2020-11-26 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0005_auto_20201125_2139'),
        ('produtos', '0023_auto_20201125_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processador',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informacoes.marcas'),
        ),
    ]
