# Generated by Django 3.1.1 on 2020-11-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0003_auto_20201123_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamanhos',
            name='tamanho',
            field=models.CharField(choices=[('4', '4 GB'), ('8', '8 GB'), ('16', '16 GB'), ('32', '32 GB'), ('64', '64 GB')], max_length=100),
        ),
    ]
