# Generated by Django 3.1.1 on 2020-11-26 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0005_auto_20201125_2139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marcas',
        ),
    ]
