# Generated by Django 3.1.3 on 2020-11-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(choices=[('Padrao', 'Padrao'), ('Azul', 'azul'), ('Branco', 'branco'), ('Preto', 'preto'), ('Vermelho', 'Vermelho')], max_length=100)),
            ],
            options={
                'verbose_name': 'Cor',
                'verbose_name_plural': 'Cores',
            },
        ),
    ]
