# Generated by Django 3.1.1 on 2020-11-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cores',
            name='cor',
            field=models.CharField(choices=[('Padrao', 'Padrao'), ('Azul', 'azul'), ('Branco', 'branco'), ('Preto', 'preto'), ('Vermelho', 'Vermelho')], max_length=100),
        ),
    ]
