# Generated by Django 3.1.3 on 2020-11-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acessorios', '0002_auto_20201117_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cores',
            options={'verbose_name': 'Cor', 'verbose_name_plural': 'Cores'},
        ),
    ]
