# Generated by Django 3.1.3 on 2020-11-16 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0003_auto_20201116_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Montagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.memoriaram')),
                ('placadevideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.placadevideo')),
                ('placamae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.placamae')),
                ('processador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.processador')),
            ],
            options={
                'verbose_name': 'Montagem',
                'verbose_name_plural': 'Montagens',
            },
        ),
    ]
