# Generated by Django 3.1.3 on 2021-01-21 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='montagem',
            old_name='placamae',
            new_name='placa_mae',
        ),
        migrations.RenameField(
            model_name='montagem',
            old_name='placadevideo',
            new_name='placade_video',
        ),
    ]
