# Generated by Django 3.1.1 on 2020-11-24 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0013_auto_20201120_1830'),
        ('montagem', '0002_auto_20201117_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montagem',
            name='memoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.memoriaram'),
        ),
        migrations.AlterField(
            model_name='montagem',
            name='nome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='montagem',
            name='placadevideo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.placadevideo'),
        ),
        migrations.AlterField(
            model_name='montagem',
            name='placamae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.placamae'),
        ),
        migrations.AlterField(
            model_name='montagem',
            name='processador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.processador'),
        ),
    ]
