# Generated by Django 3.1.1 on 2020-11-25 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0021_remove_placadevideo_none'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('montagem', '0003_auto_20201124_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montagem',
            name='memoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.memoriaram'),
        ),
        migrations.AlterField(
            model_name='montagem',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='montagem',
            name='placamae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.placamae'),
        ),
        migrations.AlterField(
            model_name='montagem',
            name='processador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.processador'),
        ),
    ]
