# Generated by Django 3.1.1 on 2020-11-26 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0025_auto_20201125_2208'),
        ('montagem', '0004_auto_20201125_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montagem',
            name='memoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.memoriaram'),
        ),
    ]
