# Generated by Django 3.1.2 on 2021-01-26 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0004_auto_20210126_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='montagem',
            old_name='nome_usuario',
            new_name='usuario_id',
        ),
    ]
