# Generated by Django 3.1.2 on 2021-01-26 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0005_auto_20210126_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='montagem',
            old_name='memoria',
            new_name='memoria_id',
        ),
        migrations.RenameField(
            model_name='montagem',
            old_name='placa_de_video',
            new_name='placa_de_video_id',
        ),
        migrations.RenameField(
            model_name='montagem',
            old_name='placa_mae',
            new_name='placa_mae_id',
        ),
        migrations.RenameField(
            model_name='montagem',
            old_name='processador',
            new_name='processador_id',
        ),
    ]
