# Generated by Django 3.1.2 on 2021-02-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20210121_0315'),
        ('montagem', '0006_auto_20210126_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montagem',
            name='memoria_id',
        ),
        migrations.AddField(
            model_name='montagem',
            name='memoria_id',
            field=models.ManyToManyField(blank=True, null=True, to='produtos.MemoriaRam'),
        ),
    ]
