# Generated by Django 3.1.2 on 2021-02-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20210121_0315'),
        ('montagem', '0007_auto_20210204_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montagem',
            name='memoria_id',
            field=models.ManyToManyField(to='produtos.MemoriaRam'),
        ),
    ]
