# Generated by Django 3.1.1 on 2020-11-18 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campos',
            options={'verbose_name': 'Campo', 'verbose_name_plural': 'Campos'},
        ),
    ]
