# Generated by Django 3.1.3 on 2020-11-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0003_clientes_nome_sobrenome'),
    ]

    operations = [
        migrations.AddField(
            model_name='nome',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sobrenome',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
