# Generated by Django 3.1.1 on 2020-11-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0004_auto_20201120_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='nome',
            name='trabalho',
            field=models.CharField(choices=[('Medico', 'medico'), ('Advogado', 'advogado')], default='Advogado', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sobrenome',
            name='trabalho',
            field=models.CharField(choices=[('Medico', 'medico'), ('Advogado', 'advogado')], default='Advogado', max_length=100),
            preserve_default=False,
        ),
    ]
