# Generated by Django 3.1.1 on 2020-11-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0005_auto_20201123_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioTeste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField(default=0)),
            ],
        ),
    ]
